version: '3.6'
services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: --check-caps false
    ports:
      - "1972:1972"
      - "52773:52773"
      - "53773:53773"
    environment:
      HOST_IP: 172.23.125.184
    volumes:
      - ./:/home/irisowner/irisdev